default: &default
  adapter: postgresql
  encoding: unicode
  username:  <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: menu_management_api_development

test:
  <<: *default
  database: menu_management_api_test

production:
  <<: *default
  database: menu_management_api_production
