# Create some sample menu items
Menu.create(name: "Margherita Pizza", price: 6.30)
Menu.create(name: "Funghi Pizza Mushroom", price: 7.00)
Menu.create(name: "Pollo Pizza Chicken", price: 7.00)
Menu.create(name: "Chicken Tikka Pizza", price: 7.00)
Menu.create(name: "Ham Pizza", price: 8.90)
Menu.create(name: "Tuna Pizza", price: 9.90)
Menu.create(name: "Pollo Fungi Pizza", price: 6.20)
Menu.create(name: "Pepperoni Pizza", price: 11.00)
Menu.create(name: "Ham & Mushroom Pizza", price: 12.30)
Menu.create(name: "Mexicana Pizza", price: 6.90)
Menu.create(name: "Donner Pizza", price: 8.90)
Menu.create(name: "Bolognese Pizza", price: 11.50)
Menu.create(name: "Smoky Bacon Pizza", price: 12.0)
Menu.create(name: "Bacon Pizza", price: 9.50)
Menu.create(name: "Chicken Tikka Special Pizza", price: 9.0)
Menu.create(name: "Hawaiian Pizza", price: 10.50)
Menu.create(name: "BBQ Chicken Pizza", price: 3.50)
Menu.create(name: "Hot Shot Pizza", price: 4.40)
Menu.create(name: "Tropicana Pizza", price: 4.60)
Menu.create(name: "Pro Fungi Pizza", price: 8.40)
Menu.create(name: "Pollo Special Pizza", price: 9.0)
Menu.create(name: "Mexican Pollo Pizza", price: 9.80)
Menu.create(name: "Chicken & Sweetcorn Pizza", price: 12.20)
Menu.create(name: "Chicken Special Pizza", price: 5.80)
Menu.create(name: "Americano Pizza", price: 7.70)
Menu.create(name: "Special Bacon Pizza", price: 12.0)
Menu.create(name: "Spicy Tuna Pizza", price: 8.40)
Menu.create(name: "Chilli Con Carne Pizza", price: 8.0)
Menu.create(name: "Chicken Doner Pizza", price: 10.0)
Menu.create(name: "Hot Pepperoni Pizza", price: 9.0)
Menu.create(name: "Vegetarian Pizza", price: 5.50)
Menu.create(name: "Sweet Vegetarian Pizza", price: 6.90)
Menu.create(name: "Meat Feast Classic Pizza", price: 10.50)
Menu.create(name: "Meat Feast Pizza", price: 8.50)
Menu.create(name: "Chicken Tikka Supreme Pizza", price: 9.0)
Menu.create(name: "Seafood Pizza", price: 6.60)
Menu.create(name: "Texas BBQ Pizza", price: 7.50)
Menu.create(name: "Costa Rica Special Pizza", price: 8.00)
Menu.create(name: "Special Pizza", price: 11.60)